services:

  db:
    image: postgres:15
    container_name: skillsup-db
    environment:
      POSTGRES_DB: skillsup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: skillsup-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/skillsup
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data: